version: '3.8'
services:
  app:
    image: jc5x/firefly-iii:latest
    environment:
      - APP_URL=${RENDER_EXTERNAL_HOSTNAME:https://your-app.onrender.com}
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always
  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=firefly
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data:
